### ISSUE TITLE
Slider disabled when user change the size indicator 

### ISSUE THREAD

**Issue by k6Labz** [VS-work/gapminder-offline#24]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart 

**PLATFORM:** 
* Bubble Chart (Offline)

**STEPS TO REPRODUCE:**
1) Open the offline Gapminder page 
2) Click on size 
3) Select Health-> Causes of newborn deaths-> Pneumonia deaths in new born 
4) Observe the slider 

**ACTUAL RESULTS:**
Slider gets disabled when user change the indicator from size dropdown

**EXPECTED RESULTS:**
Slider should remain enabled 

**SCREENSHOT:**

![1-5-2017 9-21-39 am](https://cloud.githubusercontent.com/assets/9950837/21670053/ffb7d99e-d332-11e6-91a3-215331f54bb1.jpg)

**Comment by angieskazka** [comment]
@k6Labz @korel-san @vvpanchenko 
this is correct. data is only available for 2008

**Comment by k6Labz** [comment]
But when same indicator selected on stage the data is available
